name: Publish NuGet Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Documento.Net

      - name: Build project
        run: dotnet build Documento.Net --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test Documento.Net.Tests --configuration Release --no-build --logger trx

      - name: Pack project
        run: dotnet pack Documento.Net --configuration Release --no-build -o ./nupkg

      - name: Publish NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
